name: "Test"
on:
  pull_request:
  push:
jobs:
  tests:
    strategy:
      matrix:
        platform:
          - ubuntu-latest
          - macos-latest
        channel:
          - "https://nixos.org/channels/nixos-20.03"
    runs-on: ${{ matrix.platform }}
    steps:
    - uses: actions/checkout@v1
    - uses: cachix/install-nix-action@v8
    - run: nix-channel --add ${{ matrix.channel }} nixpkgs
    - run: nix-channel --update
    - uses: cachix/cachix-action@v6
      with:
        name: finalfusion
        signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
    - run: nix-build ci.nix -A buildOutputs
    - run: nix eval -f default.nix 'lib'
    - run: nix eval -f default.nix 'modules'
    - run: nix eval -f default.nix 'overlays'
